### ISSUE TITLE
Add unit/integration test(s) for all GC events

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-native-metrics#203]
## Is your feature request related to a problem? Please describe.
In #202 it was discovered during manually testing that not all GC metrics were getting created. This is because the enum mapping changed and we were out of sync.  It was asked to write a test and I could not reliably affect all the GC metrics.

## Feature Description
Add unit/integration test(s) that assert all the GC types are getting created: Scavenge, MinorMarkCompact, MarkSweepCompact, IncrementalMarking, ProcessWeakCallbacks, and All.

## Additional context
I could not reliably get all events even with create different data types and keep them hanging around or delete refences

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Nice to Have, Really Want, Must Have, Blocker]

**Comment by jsumners-nr** [comment]
If we utilize `--expose-gc` when starting Node, we can force collections by `gc({ type: 'major' }` and `gc({ type: 'minor' })`. But that doesn't mean the sub-types, e.g. `IncrementalMarking`, would be triggered. In order to effectively test this, we would have to devise some sort of complicated script that would force entities into the correct states for sweeps. That approach would also be flaky because the garbage collector is part of V8 that is under continual improvement and is thus a moving target.

Given that, I recommend we skip this issue until we have specific issues to investigate.

-----

This script _almost_ gives us the basic major vs minor events:

```js
'use strict'

const { performance, PerformanceObserver } = require('node:perf_hooks')

const obs = new PerformanceObserver(list => {
  console.log('observer callback')
  const entries = list.getEntries()
  for (const entry of entries) {
    console.log(entry)
  }
})

obs.observe({ entryTypes: ['gc'], buffered: true })

let i = 0
let int1 = setInterval(() => {
  console.log('collecting garbage')
  gc({ type: i % 2 === 0 ? 'major' : 'minor' })
  i = i + 1
}, 1_500)

let int2 = setInterval(() => {
  let a = 1
  let b = 2
  let c = a + b
}, 500)

let int3 = setInterval(() => {
  if (i > 10) {
    clearInterval(int1)
    clearInterval(int2)
  }
}, 500)
int3.unref()

obs.disconnect()
```
