### ISSUE TITLE
Pre Build Script breaks with Webpack Compilation

### ISSUE THREAD

**Issue by krlozadan** [newrelic/node-native-metrics#70]
I'm trying to deploy an API using the serverless framework using the [Webpack plugin](https://github.com/serverless-heaven/serverless-webpack) and I get the following error when bundling:

```bash
ERROR in ./node_modules/@newrelic/native-metrics/lib/pre-build.js
Module not found: Error: Can't resolve '../package' in '/Users/usr/app/node_modules/@newrelic/native-metrics/lib'
```

The way I found to fix this is by replacing `var pkg = require('../package')` with `var pkg = require('../package.json')` in [line 47 of the pre-build.js file](https://github.com/newrelic/node-native-metrics/blob/master/lib/pre-build.js#L47)

My environment:
```bash
Operating System:          darwin
Node Version:              10.15.3
Framework Version:         1.54.0
Plugin Version:            3.1.2
SDK Version:               2.1.2
Components Core Version:   1.1.1
Components CLI Version:    1.2.3
```

I'm also using the following new relic packages to instrument my lambda functions: 
```
@newrelic/aws-sdk: 1.0.0
newrelic: 6.1.0
```

If you need more information about the environment or have any questions let me know

**Comment by krlozadan** [comment]
Also, having .json in the resolve.extensions of Webpack config helped
```
resolve: {
    extensions: ['.js', '.ts', '.json'],
},
```
So this might invalidate the the issue

**Comment by astormnewrelic** [comment]
Thanks for letting us know @krlozadan -- it looks like the `extensions` solution is the right one.  While Native node seems to pickup JSON files automatically with `require`, webpack won't load these files by default.  

With the above in place were you able to get your lambda deployed and reporting data with webpack compiled application?

**Comment by krlozadan** [comment]
Hi @astormnewrelic it works in a way... When I add the extension solution... Webpack runs out of memory if you have multiple functions and you want to package them individually.
So the scenarios where I can have it working:
1. Add the '.json' to new relic's require statement, remove the .json extension resolution from webpack and I pack functions individually
2. Keep NR require statement as is, add the **.json** extension to WP config but don't package functions individually which doesn't give us a small bundle of course

**Comment by astormnewrelic** [comment]
Thanks again for bringing this to our attention -- it sounds like [configuring webpack so it properly resolves](https://webpack.js.org/configuration/resolve/) our loading of a json file via the standard CommonJS mechanism fixed the issue.  We're going to close this out for now, but if you or the upstream provider have further thoughts please don't hesitate to let us know.

**Comment by joshua-econify** [comment]
@astormnewrelic Without additional webpack configuration this should work yes? Just need to change https://github.com/newrelic/node-native-metrics/blob/master/lib/pre-build.js#L47 to '../package.json' to use native node json imports which has had support since node v0.5. 

Out of the box this requires special config when it does not have to? Since webpack 2.0.0 json imports have been supported.

https://webpack.js.org/loaders/json-loader/
`
⚠️ Since webpack >= v2.0.0, importing of JSON files will work by default. You might still want to use this if you use a custom file extension. See the v1.0.0 -> v2.0.0 Migration Guide for more information
`

As is, this falls into the 'custom file extension' category, custom being no extension.
