### ISSUE TITLE
Convert CI to GitHub Actions

### ISSUE THREAD

**Issue by carlonewrelic** [newrelic/node-native-metrics#89]
* Users can run unit tests at a minimum.

Would aim for all tests functioning for external PR's (forked repos) with these efforts.

Ensure that the build step allows for uploading the artifact to New Relic servers.

This will be much more involved than our previous conversions.

Remove the Appveyor integration as it looks to be duplicating the Travis CI checks for Windows without upload step.  We can use github actions to run tests on Windows system.

**Comment by michaelgoin** [comment]
Thanks for getting all the notes captured here (and the others).

For this one, I think we should consider if we want to keep the auto-upload on release-tag build or switch to a different action. We may want to keep it on a release build (I think it is currently triggered by a release tag push, but might be the branch... which is slightly early) but there are other options, that we may or may not like better, such as triggering when we create a GitHub release with the release notes.

Similarly/related, we could have a GitHub workflow that posts to npm via a job and then upon success builds/uploads an artifact (or opposite order) since we'll be doing deploy work anyways.

**Comment by carlonewrelic** [comment]
Publish/deploy work added to separate issue #92
